name: Postar Frases no X

on:
  schedule:
    - cron: '0 */3 * * *' # Roda a cada 3 horas (ajuste conforme necessário)

jobs:
  postar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Instalar Dependências
        run: composer install # remova esta linha se não usar dependências PHP

      - name: Executar Script
        run: php words.php

      - name: Publicar no X
        env:
          API_KEY: ${{ secrets.X_API_KEY }}
          API_SECRET: ${{ secrets.X_API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $API_KEY" \
          -d "status=$(php words.php)" \
          https://api.twitter.com/2/tweets
